apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-service-deployment
  labels:
    app: hms-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-app
  template:
    metadata:
      labels:
        app: hms-app
    spec:
      containers:
      - name: hms-container
        image: praveenkumar4498/hms-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: hms-service
spec:
  selector:
    app: hms-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
